# fly.toml app configuration file generated for explore2coverage on 2023-11-13T01:04:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "explore2coverage"
primary_region = "ord"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["https://cnb-shim.herokuapp.com/v1/hashnuke/elixir"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
